      - name: Upload PDFs to Archive.org
        env:
          IA_ACCESS_KEY_ID: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_ACCESS_KEY: ${{ secrets.IA_SECRET_KEY }}
          IA_ITEM_ID: ${{ secrets.IA_ITEM_ID }}

        run: |
          find pdf -type f -name "*.pdf" -print0 | while IFS= read -r -d '' file
          do
            echo "Uploading: $file"

            ia upload "$IA_ITEM_ID" "$file" \
              --metadata="mediatype:texts"
          done
